data:
  train_prefix: /tmp/waymo_data/training
  val_prefix: /tmp/waymo_data/validation
  label_map: label_map.py

training:
  batch_size: 16
  num_epochs: 5
  checkpoint_dir: /tmp/waymo_data/checkpoints/
  save_interval: 1

optuna:
  n_trials: 15
  timeout: 3600
