data:
  train_prefix: /tmp/waymo_data/training
  val_prefix: /tmp/waymo_data/validation
  label_map: label_map.py

training:
  num_epochs: 3
  checkpoint_dir: /tmp/waymo_data/checkpoints/
  save_interval: 1
  num_train_files: 600
  num_val_files: 200

optuna:
  n_trials: 10
  timeout: 5400
