data:
  train_prefix: /tmp/waymo_data/training
  val_prefix: /tmp/waymo_data/validation
  label_map: label_map.py

training:
  num_epochs: 4
  checkpoint_dir: /tmp/waymo_data/checkpoints/
  save_interval: 1
  num_train_files: 6000
  num_val_files: 2000

optuna:
  n_trials: 10
  timeout: 32400
