data:
  train_prefix: /tmp/waymo_data/training
  val_prefix: /tmp/waymo_data/validation
  test_prefix: /tmp/waymo_data/testing
  label_map: label_map.py

training:
  batch_size: 2
  num_epochs: 20
  checkpoint_dir: /tmp/waymo_data/checkpoints/final
  save_interval: 1
  early_stopping_patience: 5

files:
  num_train_files: 17996
  num_val_files: 5000
  num_test_files: 4000

optimizer:
  lr: 0.005783091708283798
  momentum: 0.747406363342594
  weight_decay: 9.713582999188212e-05
